# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       toxer
Summary:    Tox client for Sailfish
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  toxer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
Toxer is a Tox client with scalable UI targetting multiple platforms.

%prep
%setup -q -n %{name}-%{version}

%build
rm -rf rpmbuilddir
mkdir rpmbuilddir
cd rpmbuilddir
cmake \
 -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 -DCMAKE_INSTALL_PREFIX=/usr \
 -DCMAKE_INSTALL_RPATH=%{_datadir}/%{name}/lib \
 -DSAILFISHAPP=ON \
 -DCMAKE_PREFIX_PATH=extra/%{_target_cpu} \
 -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=1 \
 ..
cd ..
make -C rpmbuilddir -s -j4 %{?_smp_mflags}

%install
rm -rf %{buildroot}
echo "---> Building RPM content in buildroot: %{buildroot}"
DESTDIR=%{buildroot} make -C rpmbuilddir install
# manually copy third party shared libs to rpath
mkdir %{buildroot}/%{_datadir}/%{name}/lib
cp -r extra/%{_target_cpu}/lib/* %{buildroot}/%{_datadir}/%{name}/lib

desktop-file-install --delete-original \
  --dir %{buildroot}%{_datadir}/applications \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
