# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       toxer
Summary:    Sailfish Tox client
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    LICENSE
URL:        http://example.org/
Source0:    %{name}-%{version}.tar.bz2
Source100:  toxer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  cmake

%description
Toxer is a scalable Tox client targetting multiple platforms.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
rm -rf rpmbuilddir
mkdir rpmbuilddir
cd rpmbuilddir
cmake \
 -DCMAKE_BUILD_TYPE=RelWithDebInfo \
 -DCMAKE_INSTALL_PREFIX=/usr \
 -DSAILFISHAPP=ON \
 -DCMAKE_PREFIX_PATH=extra/%{_target_cpu} \
 -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=1 \
 ..
cd ..
make -C rpmbuilddir -s -j4 %{?_smp_mflags}
# << build pre

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir install
#mkdir -p %{_bindir}
mkdir -p %{buildroot}%{_libdir}
echo "----------> buildroot: %{buildroot}"
cp -r extra/%{_target_cpu}/lib/* %{buildroot}%{_libdir}
# << install pre

# >> install post
# << install post
desktop-file-install --delete-original \
  --dir %{buildroot}%{_datadir}/applications \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_libdir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files

